# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 720
cpus_per_task: 16
gpus_per_node: null
tasks_per_node: 2
mem_gb: null
nodes: 1
name: ${hydra.job.name}
partition: short #long #long #short #
#time: 24:00:00
gres: gpu:1
cpus_per_gpu: null
gpus_per_task: null
#mem_per_cpu: 10G
#mem_per_gpu: 20G
account: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters:
  mail-user: ${oc.env:SLURM_EMAIL}
  mail-type: "BEGIN,END,FAIL,TIME_LIMIT"
  clusters: "htc"
  #error: ./logs/%j_error.log
  #output: ./logs/%j_output.log
  #dependency?
array_parallelism:  256
setup: null

# strdocs: https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py
