# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - override launcher: arc
  - override sweeper: basic

job:
  name: ${meta.experiment_name}_${meta.experiment_id}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log

mode: MULTIRUN

run:
  dir: ${paths.experiment_path}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}

sweep:
  dir: ${paths.experiment_path}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}

verbose: true
