model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  monitor: "val_total_loss"
  mode: "min"
  save_top_k: 1
  save_last: True
  filename: "model-{epoch:02d}-{val_total_loss:.2f}"
  every_n_epochs: 10

# need to have version number/linked to wandb and csv.
